name: Daily Update README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Date in README
        run: |
          NOW=$(date "+%Y-%m-%d %H:%M:%S")
          CONTENT="最后更新时间: $NOW"
          perl -0777 -pi -e "s/()(.*?)()/\$1\n$CONTENT\n\$3/s" README.md

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          if [[ -n $(git status -s) ]]; then
            git add README.md
            git commit -m "Auto update README time"
            git push
            echo "✅ README updated successfully."
          else
            echo "⚠️ No changes to commit."
          fi
